/*
  # Create user_data table for Statisty

  1. New Tables
    - `user_data`
      - `id` (bigint, primary key)
      - `created_at` (timestamp with time zone)
      - `user_id` (uuid, references auth.users)
      - `height_cm` (smallint)
      - `weight_kg` (smallint)
      - `sleep_hours` (numeric)
      - `hydration_liters` (numeric)
      - `carbon_footprint` (numeric)

  2. Security
    - Enable RLS on `user_data` table
    - Add policies for authenticated users to manage their own data
*/

create table if not exists public.user_data (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  user_id uuid references auth.users(id),
  height_cm smallint,
  weight_kg smallint,
  sleep_hours numeric,
  hydration_liters numeric,
  carbon_footprint numeric
);

alter table user_data enable row level security;

create policy "Users can insert their own data"
  on user_data
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can view their own data"
  on user_data
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can update their own data"
  on user_data
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);